// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASVcfAw1wSLHu6zCqTKKxFTYeJhIGHBno',
    appId: '1:619513274830:web:4a20888a7877c76c6d0b9f',
    messagingSenderId: '619513274830',
    projectId: 'wanderlist-8221f',
    authDomain: 'wanderlist-8221f.firebaseapp.com',
    storageBucket: 'wanderlist-8221f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-9gc46hmDFs7VUZUmje29vloS-ijztJ0',
    appId: '1:619513274830:android:2b8d37ce5dad7ccd6d0b9f',
    messagingSenderId: '619513274830',
    projectId: 'wanderlist-8221f',
    storageBucket: 'wanderlist-8221f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTwD5ujgTdxYrtegSWC6lL9l7oZo145ag',
    appId: '1:619513274830:ios:87f162a8c80756c06d0b9f',
    messagingSenderId: '619513274830',
    projectId: 'wanderlist-8221f',
    storageBucket: 'wanderlist-8221f.appspot.com',
    iosBundleId: 'com.example.wanderlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTwD5ujgTdxYrtegSWC6lL9l7oZo145ag',
    appId: '1:619513274830:ios:4b2fced83eba13dd6d0b9f',
    messagingSenderId: '619513274830',
    projectId: 'wanderlist-8221f',
    storageBucket: 'wanderlist-8221f.appspot.com',
    iosBundleId: 'com.example.wanderlist.RunnerTests',
  );
}
